// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChTTn4E4U5VI5rouapPg7ZtVeKywx86x0',
    appId: '1:235505123204:web:a3cad2517dbd92b12367d1',
    messagingSenderId: '235505123204',
    projectId: 'policyevaluation-3af1f',
    authDomain: 'policyevaluation-3af1f.firebaseapp.com',
    storageBucket: 'policyevaluation-3af1f.firebasestorage.app',
    measurementId: 'G-8C4G35JR98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjfceshCXueZ-hSx961kW1AuCTqkhwIWM',
    appId: '1:235505123204:android:e25342180879f4ce2367d1',
    messagingSenderId: '235505123204',
    projectId: 'policyevaluation-3af1f',
    storageBucket: 'policyevaluation-3af1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANf52ov_XJzXowAAm3TQ-s3F7RCLGeUXc',
    appId: '1:235505123204:ios:2c858d762ff139562367d1',
    messagingSenderId: '235505123204',
    projectId: 'policyevaluation-3af1f',
    storageBucket: 'policyevaluation-3af1f.firebasestorage.app',
    iosBundleId: 'com.example.temp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANf52ov_XJzXowAAm3TQ-s3F7RCLGeUXc',
    appId: '1:235505123204:ios:2c858d762ff139562367d1',
    messagingSenderId: '235505123204',
    projectId: 'policyevaluation-3af1f',
    storageBucket: 'policyevaluation-3af1f.firebasestorage.app',
    iosBundleId: 'com.example.temp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChTTn4E4U5VI5rouapPg7ZtVeKywx86x0',
    appId: '1:235505123204:web:1208c4479390df282367d1',
    messagingSenderId: '235505123204',
    projectId: 'policyevaluation-3af1f',
    authDomain: 'policyevaluation-3af1f.firebaseapp.com',
    storageBucket: 'policyevaluation-3af1f.firebasestorage.app',
    measurementId: 'G-VEZYN3QWJS',
  );
}
