// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2WIsVm7JfcWOXefpXBd1uH_3nW0euR_c',
    appId: '1:224633345098:web:c7ec483f2996b12bde02b3',
    messagingSenderId: '224633345098',
    projectId: 'signin-7c4a8',
    authDomain: 'signin-7c4a8.firebaseapp.com',
    storageBucket: 'signin-7c4a8.firebasestorage.app',
    measurementId: 'G-C5LR0DY2BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5nxHIAnpMGVFZqhoEkZrTZJuHTJ5-jZg',
    appId: '1:224633345098:android:806da11813d02b82de02b3',
    messagingSenderId: '224633345098',
    projectId: 'signin-7c4a8',
    storageBucket: 'signin-7c4a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLJzaHzMIFG5qLimWEZshYL6JghAq3qtw',
    appId: '1:224633345098:ios:875c87a87d8ba13ade02b3',
    messagingSenderId: '224633345098',
    projectId: 'signin-7c4a8',
    storageBucket: 'signin-7c4a8.firebasestorage.app',
    iosBundleId: 'com.example.signLogIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLJzaHzMIFG5qLimWEZshYL6JghAq3qtw',
    appId: '1:224633345098:ios:875c87a87d8ba13ade02b3',
    messagingSenderId: '224633345098',
    projectId: 'signin-7c4a8',
    storageBucket: 'signin-7c4a8.firebasestorage.app',
    iosBundleId: 'com.example.signLogIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2WIsVm7JfcWOXefpXBd1uH_3nW0euR_c',
    appId: '1:224633345098:web:8bead233b5b33846de02b3',
    messagingSenderId: '224633345098',
    projectId: 'signin-7c4a8',
    authDomain: 'signin-7c4a8.firebaseapp.com',
    storageBucket: 'signin-7c4a8.firebasestorage.app',
    measurementId: 'G-51JJ3LQELJ',
  );
}